### ISSUE TITLE
Add Footer Section

### ISSUE THREAD

**Issue by Adarsh-K21** [Adarsh-K21/profile-app#1]

**Comment by SameepAher** [comment]
Hey I'd like to work on this issue.
Could you please provide me with some more specifications?

**Comment by ranaji038** [comment]
Hey I'd like to work on this issue.

**Comment by Adarsh-K21** [comment]
@ranaji038 @SameepAher You both can work on this issue

**Comment by SameepAher** [comment]
Do you have any content which should be displayed on the footer?

**Comment by Adarsh-K21** [comment]
@SameepAher  Try to add nav links and logos available in navbar, like, try to make the footer like any other professional website

**Comment by SameepAher** [comment]
Okay understood. I'm on it

**Comment by ranaji038** [comment]
i have resolved the issue
