### ISSUE TITLE
Make heading of hero section of homepage to left align

### ISSUE THREAD

**Issue by Adarsh-K21** [Adarsh-K21/profile-app#19]

**Comment by sri-rishi** [comment]
Hey @Adarsh-K21 you want this "Grow your business ...." to be left aligned thats it

![image](https://user-images.githubusercontent.com/72429483/195970936-d640e7c2-eedf-439d-9804-dfc3d8cb4ed9.png)

**Comment by Adarsh-K21** [comment]
ok do it

**Comment by Adarsh-K21** [comment]
follow the readme before any pr

**Comment by sri-rishi** [comment]
close Make heading of hero section of homepage to left align #19 #33
