### ISSUE TITLE
Add call to action in your social icons 

### ISSUE THREAD

**Issue by prat1k-gupta** [Adarsh-K21/profile-app#28]
![image](https://user-images.githubusercontent.com/92115707/195989292-200c979b-1042-4504-b9da-a9d645e192a2.png)

As your social don't redirect to your profiles I can add them or add the default social media platforms to make it more interactive

Can you assign me this task?

**Comment by Adarsh-K21** [comment]
I don't think it as a good issue. You can resolve the other ones. thanks
