### ISSUE TITLE
Remove Scroll Bar from the website

### ISSUE THREAD

**Issue by Adarsh-K21** [Adarsh-K21/profile-app#7]

**Comment by Harsh-garg-coder** [comment]
can you assign this issue to me?

**Comment by Adarsh-K21** [comment]
@Harsh-garg-coder ok assigned

**Comment by Harsh-garg-coder** [comment]
@Adarsh-K21 are you talking about the scroll-bar of service page?

**Comment by Adarsh-K21** [comment]
> @Adarsh-K21 are you talking about the scroll-bar of service page?

of every page

**Comment by Harsh-garg-coder** [comment]
ok @Adarsh-K21
